name: mh_3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - opencv-python
    - matplotlib